//! C-compatible host structures mirrored exactly by active WGSL declarations.

use bytemuck::{Pod, Zeroable};

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Per-dispatch uniform parameters mirrored by WGSL `RenderParams`.
pub struct GpuRenderParams {
    /// Output width.
    pub width: u32,
    /// Output height.
    pub height: u32,
    /// Samples generated by this dispatch.
    pub samples: u32,
    /// Maximum path depth.
    pub max_bounces: u32,

    /// Active sphere count.
    pub sphere_count: u32,
    /// Active triangle count.
    pub triangle_count: u32,
    /// Active material count.
    pub material_count: u32,
    /// Seed component for independent animated frames.
    pub frame_index: u32,

    /// Encoded [`toaster_scene::Background`] discriminant.
    pub background_kind: u32,
    /// Active emissive primitive count.
    pub light_count: u32,
    /// Combined approximate emitted power of sampleable primitives.
    pub total_light_weight: f32,
    /// Alignment padding.
    pub _pad0: u32,

    /// Environment-map width, or zero when unavailable.
    pub environment_width: u32,
    /// Environment-map height, or zero when unavailable.
    pub environment_height: u32,
    /// Environment radiance multiplier.
    pub environment_intensity: f32,
    /// Environment yaw in degrees.
    pub environment_rotation_degrees: f32,

    /// Samples already represented by the progressive output buffer.
    pub accumulated_samples: u32,
    /// Alignment padding.
    pub _pad1: [u32; 3],

    /// Active flattened BVH node count.
    pub bvh_node_count: u32,
    /// Active BVH primitive-reference count.
    pub bvh_primitive_count: u32,
    /// Alignment padding.
    pub _pad2: [u32; 2],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Pinhole viewport basis mirrored by WGSL `Camera`.
pub struct GpuCamera {
    /// World-space camera origin in xyz.
    pub origin: [f32; 4],
    /// World-space lower-left viewport corner in xyz.
    pub lower_left_corner: [f32; 4],
    /// Horizontal viewport span in xyz.
    pub horizontal: [f32; 4],
    /// Vertical viewport span in xyz.
    pub vertical: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Sphere storage record mirrored by WGSL `Sphere`.
pub struct GpuSphere {
    /// Center in xyz and radius in w.
    pub center_radius: [f32; 4],

    /// Material storage-array index.
    pub material_index: u32,
    /// Alignment padding.
    pub _pad0: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Triangle storage record mirrored by WGSL `Triangle`.
pub struct GpuTriangle {
    /// First vertex in xyz.
    pub v0: [f32; 4],
    /// Second vertex in xyz.
    pub v1: [f32; 4],
    /// Third vertex in xyz.
    pub v2: [f32; 4],

    /// Material storage-array index.
    pub material_index: u32,
    /// Alignment padding.
    pub _pad0: [u32; 3],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Optional smooth normals and UVs mirrored by WGSL `TriangleAttributes`.
pub struct GpuTriangleAttributes {
    /// First normal in xyz.
    pub n0: [f32; 4],
    /// Second normal in xyz.
    pub n1: [f32; 4],
    /// Third normal in xyz.
    pub n2: [f32; 4],

    /// First texture coordinate.
    pub uv0: [f32; 2],
    /// Second texture coordinate.
    pub uv1: [f32; 2],
    /// Third texture coordinate.
    pub uv2: [f32; 2],
    /// Bit zero indicates normals; bit one indicates texture coordinates.
    pub flags: u32,
    /// Alignment padding.
    pub _pad0: u32,
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Material storage record mirrored by WGSL `Material`.
pub struct GpuMaterial {
    /// Kind code: diffuse 0, metal 1, dielectric 2, emissive 3.
    pub kind: u32,
    /// Starting texel in the packed texture atlas.
    pub texture_offset: u32,
    /// Base-color texture width, or zero.
    pub texture_width: u32,
    /// Base-color texture height, or zero.
    pub texture_height: u32,

    /// Linear base color in xyz.
    pub albedo: [f32; 4],

    /// Roughness x, IOR y, emission strength z, unused w.
    pub params: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Sampleable emissive primitive mirrored by WGSL `Light`.
pub struct GpuLight {
    /// Kind code: triangle 0 or sphere 1.
    pub kind: u32,
    /// Emissive material index.
    pub material_index: u32,
    /// Alignment padding.
    pub _pad0: [u32; 2],

    /// Triangle vertex zero.
    pub v0: [f32; 4],
    /// Triangle vertex one.
    pub v1: [f32; 4],
    /// Triangle vertex two.
    pub v2: [f32; 4],
    /// Sphere center in xyz and radius in w.
    pub center_radius: [f32; 4],

    /// Primitive area x, selection weight y, cumulative weight z, unused w.
    pub area_weight_cumulative: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Flattened BVH node mirrored by WGSL `BvhNode`.
pub struct GpuBvhNode {
    /// Minimum bounds in xyz.
    pub min: [f32; 4],
    /// Maximum bounds in xyz.
    pub max: [f32; 4],

    /// Interior right-child index or leaf first-primitive index.
    pub first_or_right: u32,
    /// Leaf primitive count; zero identifies an interior node.
    pub primitive_count: u32,
    /// Alignment padding.
    pub _pad: [u32; 2],
}

#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
/// Tagged scene primitive reference mirrored by WGSL `PrimitiveRef`.
pub struct GpuPrimitiveRef {
    /// Kind code: sphere 0 or triangle 1.
    pub kind: u32,
    /// Index into the corresponding scene geometry buffer.
    pub index: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gpu_types_match_wgsl_layout_sizes() {
        assert_eq!(std::mem::size_of::<GpuRenderParams>(), 96);
        assert_eq!(std::mem::size_of::<GpuCamera>(), 64);
        assert_eq!(std::mem::size_of::<GpuSphere>(), 32);
        assert_eq!(std::mem::size_of::<GpuTriangle>(), 64);
        assert_eq!(std::mem::size_of::<GpuTriangleAttributes>(), 80);
        assert_eq!(std::mem::size_of::<GpuMaterial>(), 48);
        assert_eq!(std::mem::size_of::<GpuLight>(), 96);
        assert_eq!(std::mem::size_of::<GpuBvhNode>(), 48);
        assert_eq!(std::mem::size_of::<GpuPrimitiveRef>(), 8);
    }
}
